#!/bin/bash

#sudo rm -f *file:ObjectIdentifier*
sudo killall swift-build
sudo killall swift-driver
sudo killall swift-run

rm Package.resolved

if [ -d ".build" ]; then
cd .build
find . -maxdepth 1 ! -name x86_64-unknown-linux-gnu -type f -exec rm -f {} +
find . -maxdepth 1 ! -name x86_64-unknown-linux-gnu -type d -exec rm -rf {} +
cd x86_64-unknown-linux-gnu/debug
find . -maxdepth 1 ! -name Library -type f -exec sudo rm -f {} +
find . -maxdepth 1 ! -name Library -type d -exec sudo rm -rf {} +
fi

